[config]
reload_apps = true

[config.reload_apps_list]
kitty = true

[config.wallpaper]
command = "swwc"
arguments = []

[templates.hyprland]
input_path = '~/dotfiles/.config/matugen/templates/hyprland-colors.conf'
output_path = '~/dotfiles/.config/hypr/colors.conf'

[templates.waybar]
input_path = '~/dotfiles/.config/matugen/templates/colors.css'
output_path = '~/dotfiles/.config/waybar/colors.css'

[templates.gtk3]
input_path = '~/dotfiles/.config/matugen/templates/gtk-colors.css'
output_path = '~/dotfiles/.config/gtk-3.0/colors.css'

[templates.gtk4]
input_path = '~/dotfiles/.config/matugen/templates/gtk-colors.css'
output_path = '~/dotfiles/.config/gtk-4.0/colors.css'

[templates.qt5ct]
input_path = '~/dotfiles/.config/matugen/templates/qtct-colors.conf'
output_path = '~/dotfiles/.config/qt5ct/colors/matugen.conf'

[templates.qt6ct]
input_path = '~/dotfiles/.config/matugen/templates/qtct-colors.conf'
output_path = '~/dotfiles/.config/qt6ct/colors/matugen.conf'

[templates.kitty]
input_path = '~/dotfiles/.config/matugen/templates/kitty-colors.conf'
output_path = '~/dotfiles/.config/kitty/colors.conf'

[templates.swaync]
input_path = '~/dotfiles/.config/matugen/templates/colors.css'
output_path = '~/dotfiles/.config/swaync/colors.css'

[templates.zathura]
input_path = '~/dotfiles/.config/matugen/templates/zathura-colors'
output_path = '~/dotfiles/.config/zathura/zathurarc'

[templates.pywalfox]
input_path = '~/dotfiles/.config/matugen/templates/pywalfox-colors.json'
output_path = '~/.cache/wal/colors.json'
post_hook = '/usr/bin/pywalfox update'

[templates.rofi]
input_path = '~/dotfiles/.config/matugen/templates/rofi-colors.rasi'
output_path = '~/dotfiles/.config/rofi/matugen-colors.rasi'

