[config]
reload_apps = true

[config.reload_apps_list]
kitty = true

[config.wallpaper]
command = "/usr/bin/swwc"
arguments = []

[templates.hyprland]
input_path = '~/dotfiles/.config/matugen/templates/hyprland-colors.conf'
output_path = '~/dotfiles/.config/hypr/modules/colors.conf'

[templates.waybar]
input_path = '~/dotfiles/.config/matugen/templates/colors.css'
output_path = '~/dotfiles/.config/waybar/colors.css'

[templates.gtk3]
input_path = '~/dotfiles/.config/matugen/templates/gtk-colors.css'
output_path = '~/dotfiles/.config/gtk-3.0/colors.css'

[templates.gtk4]
input_path = '~/dotfiles/.config/matugen/templates/gtk-colors.css'
output_path = '~/dotfiles/.config/gtk-4.0/colors.css'

[templates.qt5ct]
input_path = '~/dotfiles/.config/matugen/templates/qtct-colors.conf'
output_path = '~/dotfiles/.config/qt5ct/colors/matugen.conf'

[templates.qt6ct]
input_path = '~/dotfiles/.config/matugen/templates/qtct-colors.conf'
output_path = '~/dotfiles/.config/qt6ct/colors/matugen.conf'

[templates.kitty]
input_path = '~/dotfiles/.config/matugen/templates/kitty-colors.conf'
output_path = '~/dotfiles/.config/kitty/colors.conf'

[templates.swaync]
input_path = '~/.config/matugen/templates/matugen-swaync.css'
output_path = '~/.config/swaync/matugen/matugen-swaync.css'

[templates.zathura]
input_path = '~/dotfiles/.config/matugen/templates/zathura-colors'
output_path = '~/dotfiles/.config/zathura/zathurarc'

[templates.pywalfox]
input_path = '~/dotfiles/.config/matugen/templates/pywalfox-colors.json'
output_path = '~/.cache/wal/colors.json'
post_hook = '/usr/bin/pywalfox update'

[templates.rofi]
input_path = '~/dotfiles/.config/matugen/templates/rofi-colors.rasi'
output_path = '~/dotfiles/.config/rofi/matugen-colors.rasi'

[templates.swayosd]
input_path = '~/dotfiles/.config/matugen/templates/swayosd-style.css'
output_path = '~/dotfiles/.config/swayosd/style.css'
post_hook = "pkill swayosd-server; swayosd-server &> /dev/null & disown"

[templates.spicetify]
input_path = '~/dotfiles/.config/matugen/templates/spicetify-colors.ini'
output_path = '~/dotfiles/.config/spicetify/Themes/Onepunch/color.ini'
post_hook = "spicetify apply --no-restart &> /dev/null & disown"

[templates.kvantum]
input_path = '~/.config/matugen/templates/matugen.kvconfig'
output_path = '~/dotfiles/.config/Kvantum/matugen/matugen.kvconfig'

[templates.cava]
input_path = '~/.config/matugen/templates/matugen-cava'
output_path = '~/.config/cava/config'

[templates.emacs]
input_path = "~/.config/matugen/templates/doom-matugen-theme.el"
output_path = "~/.config/doom/themes/doom-matugen-theme.el"

[templates.nvim]
input_path = "~/dotfiles/.config/matugen/templates/matugen.lua"
output_path = "~/dotfiles/.config/nvim/lua/plugins/matugen.lua"
