alias nvimdiff='nvim -d'
alias rmd='/bin/rm --recursive --force --verbose'
alias icat='kitten icat'
alias mysql='mysql --host=127.0.0.1 --port=3306'
alias ssh='kitty +kitten ssh'
alias cp='~/gitclonestuff/advcpmv/advcp -g'
alias mv='~/gitclonestuff/advcpmv/advmv -g'
alias i='yay -S'
alias is='yay -Ss'
alias s='yay -Ss'
alias pyact='source .venv/bin/activate.fish'
alias ppt2pdf='libreoffice --headless --convert-to pdf'
alias emacsd='emacs --daemon'
alias ls='lsd'
alias l='lsd -l'
alias em='emacsclient'
alias tree='tree -CAhF --dirsfirst'
alias fzf="fzf --preview='bat --color=always {}'"

alias archdays='echo (math (math (date +%s) - (date -d (sudo tune2fs -l /dev/nvme0n1p1 | grep "Filesystem created" | awk \'{print $3, $4, $5, $6, $7}\') +%s)) / 86400)'
alias list_packages_by_time='lsd -lt /var/lib/pacman/local | awk \'{print $9}\''
