#!/bin/bash

if [[ $1 -eq 0 ]]; then
    DEVICE=""
    BRIGHTNESS=$(brightnessctl get)
    MAX_BRIGHTNESS=$(brightnessctl max)
elif [[ $1 -eq 1 ]]; then
    DEVICE="Monitor"
    BRIGHTNESS=$(ddcutil getvcp 10 --bus 3 | awk -F'=' '{ print $2 }' | awk -F',' '{print $1}')
    MAX_BRIGHTNESS=$(ddcutil getvcp 10 --bus 3 | awk -F'=' '/Brightness/ { gsub(/,/, "", $3); print $3 }')
else
    echo "Usage: $0 [0|1]"
    exit 1
fi

BRIGHTNESS_PERCENT=$((BRIGHTNESS * 100 / MAX_BRIGHTNESS))

# Choose icon
if [ "$BRIGHTNESS_PERCENT" -lt 30 ]; then
    ICON="brightness_low_dark"
elif [ "$BRIGHTNESS_PERCENT" -lt 70 ]; then
    ICON="brightness_medium_dark"
else
    ICON="brightness_high_dark"
fi

# swayosd-client --custom-icon="$ICON" \
#                --custom-progress= \
#                --custom-progress-text="$BRIGHTNESS_PERCENT%"

avizo-client --image-resource="$ICON" \
    --progress=$(echo "scale=2; $BRIGHTNESS_PERCENT / 100" | bc)
