#!/usr/bin/env bash

word=${1:-$(wl-paste --primary)}

query=$(curl -s --get \
  --data-urlencode "word=$word" \
  "https://api.dictionaryapi.dev/api/v2/entries/en_US/$word")

[ -z "$query" ] && notify-send -h string:bgcolor:#bf616a -t 2000 "Invalid word." && exit 0

def=$(echo "$query" | jq -r '
.[0].meanings[] |
"\(.partOfSpeech): \(.definitions[0].definition)\n"
')

notify-send -t 10000 "$word" "$def"
