#!/bin/bash

STATE="$HOME/.config/hypr/state.lua"

layout=$(
    printf "%s\n" \
        screen1 \
        screen2 \
        mult \
        mirror |
        rofi \
            -kb-element-prev "Ctrl+[45]" \
            -kb-element-next "Ctrl+[44]" \
            -dmenu
)

[ -z "$layout" ] && exit

sed -i \
    "s/layout *= *\"[^\"]*\"/layout = \"$layout\"/" \
    "$STATE"

hyprctl reload
