#!/usr/bin/env bash

SHADER_DIR="$HOME/.config/hypr/modules/shaders"
CONF_FILE="$HOME/.config/hypr/modules/shader.conf"

choice=$(printf "Night Mode\nDark Room\nFocus Mode\nDisable Shader" | rofi -kb-element-prev "Ctrl+[45]" -kb-element-next "Ctrl+[44]" -dmenu -p "Screen Shader")

case "$choice" in
"Night Mode")
  shader="$SHADER_DIR/nightMode.frag"
  ;;
"Dark Room")
  shader="$SHADER_DIR/darkRoom.frag"
  ;;
"Focus Mode")
  shader="$SHADER_DIR/focusMode.frag"
  ;;
"Disable Shader")
  shader=""
  ;;
*)
  exit 0
  ;;
esac

if [ -z "$shader" ]; then
  cat >"$CONF_FILE" <<EOF
decoration {
}
EOF
else
  cat >"$CONF_FILE" <<EOF
decoration {
    screen_shader = $shader
}
EOF
fi

hyprctl reload
