#!/bin/bash
swww img $1
/home/varunadhityagb/dotfiles/.config/hypr/scripts/generate_clipse_theme.py /home/varunadhityagb/.cache/wal/colors.json /home/varunadhityagb/dotfiles/.config/clipse/custom_theme.json
