#!/bin/bash

MUTED=$(pactl get-sink-mute @DEFAULT_SINK@ | awk '{print $2}' | tr '[:upper:]' '[:lower:]')
VOL=$(pactl get-sink-volume @DEFAULT_SINK@ | awk '{print $5}' | tr -d '%')
qs ipc call osd volume $VOL $MUTED
