#!/bin/bash

# Get current volume and mute status
VOL=$(pamixer --get-volume)
MUTE=$(pamixer --get-mute)

# Choose appropriate icon
if [ "$MUTE" = "true" ]; then
    ICON="volume_muted_dark"
elif [ "$VOL" -lt 30 ]; then
    ICON="volume_low_dark"
elif [ "$VOL" -lt 70 ]; then
    ICON="volume_medium_dark"
else
    ICON="volume_high_dark"
fi

VAL=$(awk -v vol="$VOL" 'BEGIN { printf "%.2f", vol / 100 }')

# Check if VAL > 1
if (( $(echo "$VAL > 1" | bc -l) )); then
    # Wrap value into 0–1 range
    WRAPPED_VAL=$(awk -v val="$VAL" 'BEGIN { printf "%.2f", val - int(val) }')

    avizo-client --image-resource="$ICON" \
                 --progress="$WRAPPED_VAL" \
                 --bar-fg-color=red

else
    avizo-client --image-resource="$ICON" \
                 --progress="$VAL"
fi
