#!/bin/bash

export XDG_RUNTIME_DIR="/run/user/$(id -u)"
export WAYLAND_DISPLAY="wayland-1"

hyprctl dispatch dpms on
minute=$(date +%-M)
if [[ $minute -ge 5 && $minute -le 55 ]]; then
    /usr/bin/update-wallpaper >> ~/.wall_timer_log &
fi

/usr/bin/screen_timer on
