#!/bin/bash

current_time_min=$(date +%-M)
current_time_hour=$(date +%-H)

if [[ $current_time_hour -gt 17 || $current_time_hour -lt 6 ]]; then
    time_limit=55
else
    time_limit=5
fi

if (( current_time_min <= time_limit )); then
    /usr/bin/update-wallpaper >> ~/.wall_timer_log &
    sleep 300
fi
