#!/bin/bash

# Check if Waybar is running
if pgrep -x "waybar" > /dev/null; then
    echo "Waybar is running. Killing it..."
    killall waybar
else
    echo "Waybar is not running. Starting it..."
    waybar &
fi
