
$image = /home/varunadhityagb/Wallpaper/3.png
$background = rgb(101418)

$image = /home/varunadhityagb/Wallpaper/3.png
$error = rgb(ffb4ab)

$image = /home/varunadhityagb/Wallpaper/3.png
$error_container = rgb(93000a)

$image = /home/varunadhityagb/Wallpaper/3.png
$inverse_on_surface = rgb(2d3135)

$image = /home/varunadhityagb/Wallpaper/3.png
$inverse_primary = rgb(2b638b)

$image = /home/varunadhityagb/Wallpaper/3.png
$inverse_surface = rgb(e0e2e8)

$image = /home/varunadhityagb/Wallpaper/3.png
$on_background = rgb(e0e2e8)

$image = /home/varunadhityagb/Wallpaper/3.png
$on_error = rgb(690005)

$image = /home/varunadhityagb/Wallpaper/3.png
$on_error_container = rgb(ffdad6)

$image = /home/varunadhityagb/Wallpaper/3.png
$on_primary = rgb(003351)

$image = /home/varunadhityagb/Wallpaper/3.png
$on_primary_container = rgb(cce5ff)

$image = /home/varunadhityagb/Wallpaper/3.png
$on_primary_fixed = rgb(001e31)

$image = /home/varunadhityagb/Wallpaper/3.png
$on_primary_fixed_variant = rgb(054b72)

$image = /home/varunadhityagb/Wallpaper/3.png
$on_secondary = rgb(23323f)

$image = /home/varunadhityagb/Wallpaper/3.png
$on_secondary_container = rgb(d4e4f6)

$image = /home/varunadhityagb/Wallpaper/3.png
$on_secondary_fixed = rgb(0d1d2a)

$image = /home/varunadhityagb/Wallpaper/3.png
$on_secondary_fixed_variant = rgb(394857)

$image = /home/varunadhityagb/Wallpaper/3.png
$on_surface = rgb(e0e2e8)

$image = /home/varunadhityagb/Wallpaper/3.png
$on_surface_variant = rgb(c2c7ce)

$image = /home/varunadhityagb/Wallpaper/3.png
$on_tertiary = rgb(372a4a)

$image = /home/varunadhityagb/Wallpaper/3.png
$on_tertiary_container = rgb(ecdcff)

$image = /home/varunadhityagb/Wallpaper/3.png
$on_tertiary_fixed = rgb(211534)

$image = /home/varunadhityagb/Wallpaper/3.png
$on_tertiary_fixed_variant = rgb(4e4162)

$image = /home/varunadhityagb/Wallpaper/3.png
$outline = rgb(8c9198)

$image = /home/varunadhityagb/Wallpaper/3.png
$outline_variant = rgb(42474e)

$image = /home/varunadhityagb/Wallpaper/3.png
$primary = rgb(98ccf9)

$image = /home/varunadhityagb/Wallpaper/3.png
$primary_container = rgb(054b72)

$image = /home/varunadhityagb/Wallpaper/3.png
$primary_fixed = rgb(cce5ff)

$image = /home/varunadhityagb/Wallpaper/3.png
$primary_fixed_dim = rgb(98ccf9)

$image = /home/varunadhityagb/Wallpaper/3.png
$scrim = rgb(000000)

$image = /home/varunadhityagb/Wallpaper/3.png
$secondary = rgb(b8c8da)

$image = /home/varunadhityagb/Wallpaper/3.png
$secondary_container = rgb(394857)

$image = /home/varunadhityagb/Wallpaper/3.png
$secondary_fixed = rgb(d4e4f6)

$image = /home/varunadhityagb/Wallpaper/3.png
$secondary_fixed_dim = rgb(b8c8da)

$image = /home/varunadhityagb/Wallpaper/3.png
$shadow = rgb(000000)

$image = /home/varunadhityagb/Wallpaper/3.png
$source_color = rgb(0b3f5f)

$image = /home/varunadhityagb/Wallpaper/3.png
$surface = rgb(101418)

$image = /home/varunadhityagb/Wallpaper/3.png
$surface_bright = rgb(363a3e)

$image = /home/varunadhityagb/Wallpaper/3.png
$surface_container = rgb(1c2024)

$image = /home/varunadhityagb/Wallpaper/3.png
$surface_container_high = rgb(272a2e)

$image = /home/varunadhityagb/Wallpaper/3.png
$surface_container_highest = rgb(313539)

$image = /home/varunadhityagb/Wallpaper/3.png
$surface_container_low = rgb(181c20)

$image = /home/varunadhityagb/Wallpaper/3.png
$surface_container_lowest = rgb(0b0f12)

$image = /home/varunadhityagb/Wallpaper/3.png
$surface_dim = rgb(101418)

$image = /home/varunadhityagb/Wallpaper/3.png
$surface_tint = rgb(98ccf9)

$image = /home/varunadhityagb/Wallpaper/3.png
$surface_variant = rgb(42474e)

$image = /home/varunadhityagb/Wallpaper/3.png
$tertiary = rgb(d1bfe7)

$image = /home/varunadhityagb/Wallpaper/3.png
$tertiary_container = rgb(4e4162)

$image = /home/varunadhityagb/Wallpaper/3.png
$tertiary_fixed = rgb(ecdcff)

$image = /home/varunadhityagb/Wallpaper/3.png
$tertiary_fixed_dim = rgb(d1bfe7)

